CREATE TABLE expense(
    id BIGINT(19) PRIMARY KEY AUTO_INCREMENT,
    type_movement VARCHAR(20) NOT NULL,
    value DECIMAL(9,5) NOT NULL DEFAULT 0.0,
    description VARCHAR(150) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE saving(
    id BIGINT(19) PRIMARY KEY AUTO_INCREMENT,
    type_movement VARCHAR(20) NOT NULL,
    value DECIMAL(9,5) NOT NULL DEFAULT 0.0,
    description VARCHAR(150) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;